global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']
    basic_auth:
      username: 'admin'
      password: 'password'

  - job_name: 'celery_worker_1'
    metrics_path: /
    static_configs:
      - targets: ['celery_worker_1:8001']

  - job_name: 'celery_worker_2'
    metrics_path: /
    static_configs:
      - targets: ['celery_worker_2:8002']